services:
  db:
    image: postgres:15.2-bullseye
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/

volumes:
  db_data: